output:
  html: report/report.html
  json: report/report.json
  markdown: report/report.md
expected-metrics-change:
  dataless: 0.2
  applications: 0.2
  formations: 0.1
  dispatches: 0.2
expected-improved-programs-percentage: 0.9
items:
- phi: pipeline/phi/as-phi-tests.phi
  phi-normalized: pipeline/phi-normalized/as-phi-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/bool-tests.phi
  phi-normalized: pipeline/phi-normalized/bool-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/bytes-tests.phi
  phi-normalized: pipeline/phi-normalized/bytes-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/cage-tests.phi
  phi-normalized: pipeline/phi-normalized/cage-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/cti-test.phi
  phi-normalized: pipeline/phi-normalized/cti-test.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/dataized-tests.phi
  phi-normalized: pipeline/phi-normalized/dataized-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/float-tests.phi
  phi-normalized: pipeline/phi-normalized/float-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/goto-tests.phi
  phi-normalized: pipeline/phi-normalized/goto-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/int-tests.phi
  phi-normalized: pipeline/phi-normalized/int-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/io/stdout-tests.phi
  phi-normalized: pipeline/phi-normalized/io/stdout-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/malloc-tests.phi
  phi-normalized: pipeline/phi-normalized/malloc-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/nan-tests.phi
  phi-normalized: pipeline/phi-normalized/nan-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/negative-infinity-tests.phi
  phi-normalized: pipeline/phi-normalized/negative-infinity-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/positive-infinity-tests.phi
  phi-normalized: pipeline/phi-normalized/positive-infinity-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/runtime-tests.phi
  phi-normalized: pipeline/phi-normalized/runtime-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
# - phi: pipeline/phi/rust-tests.phi
#   phi-normalized: pipeline/phi-normalized/rust-tests.phi
#   bindings-path-phi: org.eolang
#   bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/seq-tests.phi
  phi-normalized: pipeline/phi-normalized/seq-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/string-tests.phi
  phi-normalized: pipeline/phi-normalized/string-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/switch-tests.phi
  phi-normalized: pipeline/phi-normalized/switch-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/try-tests.phi
  phi-normalized: pipeline/phi-normalized/try-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/tuple-tests.phi
  phi-normalized: pipeline/phi-normalized/tuple-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
- phi: pipeline/phi/while-tests.phi
  phi-normalized: pipeline/phi-normalized/while-tests.phi
  bindings-path-phi: org.eolang
  bindings-path-phi-normalized: org.eolang
