report:
  output:
    html: pipeline/report/report.html
    json: pipeline/report/report.json
    markdown: pipeline/report/report.md
  expected-metrics-change:
    dataless: 0.2
    applications: 0.2
    formations: 0.1
    dispatches: 0.2
  expected-improved-programs-percentage: 0.9
items:
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/as-phi-tests.eo
    yaml: pipeline/yaml/as-phi-tests.yaml
    destination: pipeline/eo/as-phi-tests.eo
  phi:
    initial: pipeline/phi/as-phi-tests.eo
    normalized: pipeline/phi-normalized/as-phi-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/bool-tests.eo
    yaml: pipeline/yaml/bool-tests.yaml
    destination: pipeline/eo/bool-tests.eo
  phi:
    initial: pipeline/phi/bool-tests.eo
    normalized: pipeline/phi-normalized/bool-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/bytes-tests.eo
    yaml: pipeline/yaml/bytes-tests.yaml
    destination: pipeline/eo/bytes-tests.eo
  phi:
    initial: pipeline/phi/bytes-tests.eo
    normalized: pipeline/phi-normalized/bytes-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/cage-tests.eo
    yaml: pipeline/yaml/cage-tests.yaml
    destination: pipeline/eo/cage-tests.eo
  phi:
    initial: pipeline/phi/cage-tests.eo
    normalized: pipeline/phi-normalized/cage-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/cti-test.eo
    yaml: pipeline/yaml/cti-test.yaml
    destination: pipeline/eo/cti-test.eo
  phi:
    initial: pipeline/phi/cti-test.phi
    normalized: pipeline/phi-normalized/cti-test.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/dataized-tests.eo
    yaml: pipeline/yaml/dataized-tests.yaml
    destination: pipeline/eo/dataized-tests.eo
  phi:
    initial: pipeline/phi/dataized-tests.eo
    normalized: pipeline/phi-normalized/dataized-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/float-tests.eo
    yaml: pipeline/yaml/float-tests.yaml
    destination: pipeline/eo/float-tests.eo
  phi:
    initial: pipeline/phi/float-tests.eo
    normalized: pipeline/phi-normalized/float-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/goto-tests.eo
    yaml: pipeline/yaml/goto-tests.yaml
    destination: pipeline/eo/goto-tests.eo
  phi:
    initial: pipeline/phi/goto-tests.eo
    normalized: pipeline/phi-normalized/goto-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/int-tests.eo
    yaml: pipeline/yaml/int-tests.yaml
    destination: pipeline/eo/int-tests.eo
  phi:
    initial: pipeline/phi/int-tests.eo
    normalized: pipeline/phi-normalized/int-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/io/stdout-tests.eo
    yaml: pipeline/yaml/io/stdout-tests.yaml
    destination: pipeline/eo/io/stdout-tests.eo
  phi:
    initial: pipeline/phi/io/stdout-tests.eo
    normalized: pipeline/phi-normalized/io/stdout-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/malloc-tests.eo
    yaml: pipeline/yaml/malloc-tests.yaml
    destination: pipeline/eo/malloc-tests.eo
  phi:
    initial: pipeline/phi/malloc-tests.eo
    normalized: pipeline/phi-normalized/malloc-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/nan-tests.eo
    yaml: pipeline/yaml/nan-tests.yaml
    destination: pipeline/eo/nan-tests.eo
  phi:
    initial: pipeline/phi/nan-tests.eo
    normalized: pipeline/phi-normalized/nan-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/negative-infinity-tests.eo
    yaml: pipeline/yaml/negative-infinity-tests.yaml
    destination: pipeline/eo/negative-infinity-tests.eo
  phi:
    initial: pipeline/phi/negative-infinity-tests.eo
    normalized: pipeline/phi-normalized/negative-infinity-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/positive-infinity-tests.eo
    yaml: pipeline/yaml/positive-infinity-tests.yaml
    destination: pipeline/eo/positive-infinity-tests.eo
  phi:
    initial: pipeline/phi/positive-infinity-tests.eo
    normalized: pipeline/phi-normalized/positive-infinity-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo
    yaml: pipeline/yaml/runtime-tests.yaml
    destination: pipeline/eo/runtime-tests.eo
  phi:
    initial: pipeline/phi/runtime-tests.eo
    normalized: pipeline/phi-normalized/runtime-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/rust-tests.eo
    yaml: pipeline/yaml/rust-tests.yaml
    destination: pipeline/eo/rust-tests.eo
  phi:
    initial: pipeline/phi/rust-tests.eo
    normalized: pipeline/phi-normalized/rust-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
  enable: false
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/seq-tests.eo
    yaml: pipeline/yaml/seq-tests.yaml
    destination: pipeline/eo/seq-tests.eo
  phi:
    initial: pipeline/phi/seq-tests.eo
    normalized: pipeline/phi-normalized/seq-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/string-tests.eo
    yaml: pipeline/yaml/string-tests.yaml
    destination: pipeline/eo/string-tests.eo
  phi:
    initial: pipeline/phi/string-tests.eo
    normalized: pipeline/phi-normalized/string-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/switch-tests.eo
    yaml: pipeline/yaml/switch-tests.yaml
    destination: pipeline/eo/switch-tests.eo
  phi:
    initial: pipeline/phi/switch-tests.eo
    normalized: pipeline/phi-normalized/switch-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/try-tests.eo
    yaml: pipeline/yaml/try-tests.yaml
    destination: pipeline/eo/try-tests.eo
  phi:
    initial: pipeline/phi/try-tests.eo
    normalized: pipeline/phi-normalized/try-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/tuple-tests.eo
    yaml: pipeline/yaml/tuple-tests.yaml
    destination: pipeline/eo/tuple-tests.eo
  phi:
    initial: pipeline/phi/tuple-tests.eo
    normalized: pipeline/phi-normalized/tuple-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    source: eo/eo-runtime/src/test/eo/org/eolang/while-tests.eo
    yaml: pipeline/yaml/while-tests.yaml
    destination: pipeline/eo/while-tests.eo
  phi:
    initial: pipeline/phi/while-tests.eo
    normalized: pipeline/phi-normalized/while-tests.eo
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
