[book]
authors = ["Danila Danko"]
language = "en"
multilingual = false
src = "src"
title = "phi-normalizer"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[build]
build-dir = "./docs"
